name: My First GitHub Actions Workflow

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test
        run: echo "Running tests..."

      - name: Test successful
        run: echo "Tests passed!"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building application..."

      - name: Build successful
        run: echo "Build completed!"